name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: w3c/spec-prod@v2

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "proposal-webcrypto-streams"
          entrypoint: "https://deno.land/std@0.134.0/http/file_server.ts"
